org.gradle.jvmargs=-Xmx2G

maven_group=com.terraformersmc
archives_base_name=traverse
mod_version=dev
single_platform=fabric

minecraft_version=26.2
loader_version=0.19.3
fabric_version=0.153.0+26.2

# Terraform APIs
terraform_biome_remapper_api_version=17.0.0-beta.5
terraform_config_api_version=17.0.0-beta.5
terraform_surfaces_api_version=17.0.0-beta.5
terraform_tree_api_version=17.0.0-beta.5
terraform_wood_api_version=17.0.0-beta.5

# Biolith for worldgen module and testing
biolith_version=3.7.0-alpha.2

##
## Ferry configuration
##

# Project Metadata
project_name=Traverse
project_owner=Terraformers
project_url=https://modrinth.com/mod/traverse
project_logo=https://i.imgur.com/oiDJdfG.png
project_color=#00a14b
# default_release_type can be stable, beta, or alpha
default_release_type=alpha

# CurseForge Metadata
curseforge_slug=traverse
curseforge_id=308777
curseforge_game_versions=26.2
curseforge_required_dependencies=fabric-api
curseforge_optional_dependencies=
curseforge_embedded_dependencies=biolith

# Modrinth Metadata
modrinth_slug=traverse
modrinth_id=kXygSBVI
modrinth_game_versions=26.2
modrinth_mod_loaders=
modrinth_required_dependencies=fabric-api
modrinth_optional_dependencies=
modrinth_embedded_dependencies=biolith

# Discord Emotes
curseforge_emote=<:curseforge:1078567270239981628>
modrinth_emote=<:modrinth:802414390510354453>
github_emote=<:github:698031289223217152>

# Webhook Options
use_project_username=false

# Changelog Options
# changelog_hide_unimportant_commits tries to hide Merge commits
changelog_hide_unimportant_commits=true
changelog_max_commit_search=200
discord_webhook_changelog_line_limit=10
