base.archivesName = "traverse-worldgen"

loom {
	accessWidenerPath = file("src/main/resources/traverse-worldgen.accesswidener")
}

dependencies {
	// Biolith for the worldgen API module
	implementation "com.terraformersmc:biolith-fabric:${biolith_version}"

	implementation project(path: ':traverse-common')
}
